### PR TITLE
Feature - Conditions

### PR DESCRIPTION
**Pull request by Dumbgenius**
Partially addresses #13. This contains a basic UI for adding any of the standard conditions (as listed in ./lib/methods/conditions.js), listing them on the Stats page, and removing them. I've excluded the encumbrance conditions, as I assume they are supposed to be added automatically based on carry weight and encumbrance limits. I haven't yet added any ability to add or use custom conditions.

### CODE REVIEW

**Comment by Dumbgenius** [comment]
Currently the conditions library dialog does not properly animate (i.e. it does not shrink down into the newly-created condition) as I haven't quite figured out how to properly use `returnElement`.

**Comment by Dumbgenius** [comment]
I've added the model changes from #110 to the Buffs model here as well for compatibility.

**Comment by Dumbgenius** [comment]
Important question, @ThaumRystra: is it better to 
- rename the current `Buffs` collection to `Conditions` (this avoids conflicts/confusion with a future implementation of custom buffs, but is annoying to do), or 
- keep it as it is now, and instead use `CustomBuffs` and `CustomBuffTemplates` for the future custom buffs?

**Comment by ThaumRystra** [comment]
We should rename buffs into conditions, there should be nothing in the affected collections in the database now, and it's way easier to change it before there is.

**Pull request closed without merging**
