### PR TITLE
Miscellaneous enhancements

### LINKED ISSUE #26: Getting the same proficiency from multiple sources should combine in the proficiency list.

### LINKED ISSUE #58: Marker for material components with a GP cost
_"...If a cost is indicated for a component, a character must have that specific component before he or she can cast the spell."_ -PHB 203

------------------

Currently any material components only appear on the spell list as simply an M (i.e. "Evocation action - V,S,M). This is fine for when the specifics of actually having the material components can be handwaved with a component pouch or spellcasting focus - however, for spells like _chromatic orb_ or _identify_, specific components must be purchased in advance before the spell can be cast, and short of appending "[GP]" to the spell name there is currently no way of signifying this on the spell list.

I'd suggest just another letter or two on the components - for example, "Evocation action - V, S, Mgp" or "Evocation action - V, S, M, G"

### LINKED ISSUE #81: Merge multiple tool proficiencies on the features page
If different things give you the same proficiency, they should be merged on the features page

### LINKED ISSUE #86: Give cantrips in the SRD library attacks
With damage formula: `{floor((Level+1)/6)+1}d8`

### LINKED ISSUE #94: Add setting to swap stats and their modifiers
In the official character sheet, nobody can really agree which number should be in the bigger box, so DiceCloud should embrace the debate and let the character sheet have a setting to swap the two around.

Default behavior will stay with the modifier as the smaller number.

### LINKED ISSUE #116: Parties aren't sorted in either character list

### PR DESCRIPTION
**Pull request by Dumbgenius**
This branch covers the contents of #108, #111, and #113, which address #102 (partially), #107 and #94   respectively, as wells some other minor changes, such as extra loading hints.

This branch resolves #58, resolves #94, resolves #26, resolves #81 (are #26 and #81 the same issue?), resolves #86, and resolves #116. Whew, that's a lot of issue references I have to put here so they link properly.

### CODE REVIEW

**Comment by Dumbgenius** [comment]
This now addresses #26 and #81 (which appear to be the same issue?)

**Comment by Dumbgenius** [comment]
Now adresses #86

**Comment by Dumbgenius** [comment]
Now covers #117 and thus addresses #116

**Comment by ThaumRystra** [comment]
I'd like to start working on merging this branch today, so I think for now don't commit new features here, just fixes or tweaks.

**Pull request merged**
