### PR TITLE
Add raw character JSON output, improve ratelimiter rules of API

### PR DESCRIPTION
**Pull request by mommothazaz123**
This adds a ``/character/:charId/json`` endpoint to simply retrieve all collection entries associated with a character, so that applications may calculate the final results themselves. This should eliminate the need to subscribe to lazy-load characters, while retaining the same functionality.

Additionally, I added a way to define a ratelimit per-method, instead of having a global ratelimit per API key. Currently, API keys are limited to 5 requests / 5 seconds globally, then a stricter limit per endpoint.

### CODE REVIEW

**Comment by mommothazaz123** [comment]
Evidently renaming `/rpg-docs` to `/app` had some issues between my branch and the origin branch. Let me see what I can do.

**Comment by mommothazaz123** [comment]
Ok, fixed merge conflicts, removed smart-disconnect package, and added permission check on character JSON endpoint. Edited `lib/functions/permissions.js` to return true if a character was set to "anyone with link can view" as well.

**Comment by ThaumRystra** [comment]
Next 2 hours or so

**Comment by mommothazaz123** [comment]
Great, thanks!

**Comment by ThaumRystra** [comment]
Live 👍

**Pull request merged**
